#pragma once
#include <cstdint>

namespace weave::platform
{
    enum class SystemError
    {
        Success,
        AddressFamilyNotSupported,
        AddressInUse,
        AddressNotAvailable,
        AlreadyConnected,
        ArgumentListTooLong,
        ArgumentOutOfDomain,
        BadAddress,
        BadFileDescriptor,
        BadMessage,
        BrokenPipe,
        ConnectionAborted,
        ConnectionAlreadyInProgress,
        ConnectionRefused,
        ConnectionReset,
        CrossDeviceLink,
        DestinationAddressRequired,
        DeviceOrResourceBusy,
        DirectoryNotEmpty,
        ExecutableFormatError,
        FileExists,
        FileTooLarge,
        FileNameTooLong,
        FunctionNotSupported,
        HostUnreachable,
        IdentifierRemoved,
        IllegalByteSequence,
        InappropriateIoControlOperation,
        Interrupted,
        InvalidArgument,
        InvalidSeek,
        IoError,
        IsADirectory,
        MessageSize,
        NetworkDown,
        NetworkReset,
        NetworkUnreachable,
        NoBufferSpace,
        NoChildProcess,
        NoLink,
        NoLockAvailable,
        NoMessageAvailable,
        NoMessage,
        NoProtocolOption,
        NoSpaceOnDevice,
        NoStreamResources,
        NoSuchDeviceOrAddress,
        NoSuchDevice,
        NoSuchFileOrDirectory,
        NoSuchProcess,
        NotADirectory,
        NotASocket,
        NotAStream,
        NotConnected,
        NotEnoughMemory,
        NotSupported,
        OperationCanceled,
        OperationInProgress,
        OperationNotPermitted,
        OperationNotSupported,
        OperationWouldBlock,
        OwnerDead,
        PermissionDenied,
        ProtocolError,
        ProtocolNotSupported,
        ReadOnlyFileSystem,
        ResourceDeadlockWouldOccur,
        ResourceUnavailableTryAgain,
        ResultOutOfRange,
        StateNotRecoverable,
        StreamTimeout,
        TextFileBusy,
        TimedOut,
        TooManyFilesOpenInSystem,
        TooManyFilesOpen,
        TooManyLinks,
        TooManySymbolicLinkLevels,
        ValueTooLarge,
        WrongProtocolType,
        EndOfFile,
        Unknown,
    };
}

namespace weave::platform::impl
{
    SystemError SystemErrorFromErrno(int error);

    SystemError SystemErrorFromWin32Error(uint32_t error);
}
